GET http://localhost:4004/employee

###
GET http://localhost:4004/employee/Employees
Authorization: Basic manish:12345

###
GET http://localhost:4004/employee/Employees/$count
Authorization: Basic manish:12345

###
GET http://localhost:4004/employee/Employees
Authorization: Basic manish:12345


###

GET http://localhost:4004/employee/Employees
Authorization: Basic danish:2316810

###
GET http://localhost:4004/employee/Employees/$count
Authorization: Basic danish:2316810
